export const ErrorCodes = {
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_API_KEY: 'INVALID_API_KEY',
  ACCOUNT_FROZEN: 'ACCOUNT_FROZEN',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',

  // Workspace
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_SLUG_TAKEN: 'WORKSPACE_SLUG_TAKEN',

  // Account
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  PARENT_NOT_FOUND: 'PARENT_NOT_FOUND',
  MAX_AGENTS_EXCEEDED: 'MAX_AGENTS_EXCEEDED',
  PERMISSION_ESCALATION: 'PERMISSION_ESCALATION',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',

  // Channel
  CHANNEL_NOT_FOUND: 'CHANNEL_NOT_FOUND',
  NOT_SUBSCRIBED: 'NOT_SUBSCRIBED',
  ALREADY_SUBSCRIBED: 'ALREADY_SUBSCRIBED',
  PRIVATE_CHANNEL_ACCESS: 'PRIVATE_CHANNEL_ACCESS',

  // Message
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  MENTION_NOT_FOUND: 'MENTION_NOT_FOUND',
  MENTION_NOT_YOURS: 'MENTION_NOT_YOURS',
  MENTION_ALREADY_ACKED: 'MENTION_ALREADY_ACKED',

  // File
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',

  // Approval
  APPROVAL_NOT_FOUND: 'APPROVAL_NOT_FOUND',
  APPROVAL_ALREADY_DECIDED: 'APPROVAL_ALREADY_DECIDED',

  // Invitation
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_EMAIL_MISMATCH: 'INVITATION_EMAIL_MISMATCH',
  ALREADY_IN_WORKSPACE: 'ALREADY_IN_WORKSPACE',

  // General
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export class AppError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly statusCode: number = 400,
  ) {
    super(message);
    this.name = 'AppError';
  }
}
